export const SHOW_PAYMENT_FORM = 'SHOW_PAYMENT_FORM';
export const PAYMENT_FORM_CLOSED = 'PAYMENT_FORM_CLOSED';
export const ENABLE_FULLSCREEN = 'ENABLE_FULLSCREEN';
export const FULLSCREEN_MODE_CHANGED = 'FULLSCREEN_MODE_CHANGED';
